site_name: Cam and Quinn's Wedding Travel Guide
site_url: https://kurotori.land
theme:
  name: material  
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
use_directory_urls: true
strict: true
markdown_extensions:
  - footnotes
  - toc
