site_name: Cam and Quinn's Wedding Travel Guide
site_url: https://kurotori.land
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
watch:
  - docs
use_directory_urls: true
strict: true
markdown_extensions:
  - footnotes
